name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: gumroad_demo_test
          POSTGRES_USER: iainkirkpatrick
          POSTGRES_PASSWORD: gumroad
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: localhost
      DB_USERNAME: iainkirkpatrick
      DB_PASSWORD: gumroad
      RAILS_ENV: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Install Rails dependencies
      run: bundle install

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install npm dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Set up database
      run: |
        sudo apt-get install -y libpq-dev
        bin/rails db:create
        bin/rails db:schema:load

    - name: Run Rails tests
      run: |
        bin/rails test

    - name: Run Playwright tests
      run: npm run ci
